Allow multiple sass files configuration
flaviait/ng2-jspm-template-libs pull request #5
Opened 2016-12-22 07:28 UTC by svi3c

This PR provides the capability that
* Mutliple style processing configurations can be added
* Sass processing can optionally be wrapped in ES modules with default export

This way we don't have to rely on [plugin-scss](https://github.com/KevCJones/plugin-scss).

@DorianGrey

2016-12-23 12:09 UTC, DorianGrey requested changes

2016-12-23 12:09 UTC, DorianGrey commented on spec/fixtures/a.entry.scss
> +  version: 1;
I know this is just for fixtures, but ... I'd prefer real properties over custom ones.

2016-12-23 12:09 UTC, DorianGrey commented on spec/fixtures/b.scss
> +  version: 1;
Same here.

2016-12-23 12:09 UTC, DorianGrey commented on spec/fixtures/c.scss
> +  version: 1;
Same here.

2016-12-23 12:09 UTC, DorianGrey commented on src/bin/compile-styles.ts
> +console.log(params.outDir);
Is this some kind of art, or may it be dropped? 😉

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.spec.ts
> +import {beforeAll, afterAll, it, await} from "jasmine-await";
I know we're not using TypeScript 2.1 (yet), but `await` will definitely conflict with the keyword of the same name. This should be kept in mind here; Alternatively, use an alias for importing `await`.

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.spec.ts
> +          compiler.stop();
I've seen that this statement is used multiple times, so what about extracting a helper function `stopCompiler` for this?
This could be added along to the place where the compiler is instantiated, so it's easier to keep track of it.
And it would reduce most of these `afterAll` calls to `afterAll(stopCompiler)`, which is both shorter and easier to read.

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.ts
> +  private logger: log4js.Logger = StyleCompiler.logger;
Hm... why do we need the logger both as a static and as an instance variable?

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.ts
> +      filesToWatch.forEach((file: string) => watcher.unwatch(file));
Hm... I'm not sure about this one: Create a watcher for `filesToWatch`, but remove all of these files on change event?
Can you elaborate?

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.ts
> +        if (pluginConfig) {
IIRC, there are several `postcss` plugins that do not require a particular config, either because they have well-defined default values or simply don't take one at all. 
On the other hand, if someone would simply have forgotten to add this config, the corresponding plugin would just be skipped without any further notification.

I'd suggest to skip this check and just call the plugin.

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.ts
> +          map: this.config.sourceMaps && {inline: false},
What's the problem with inline source maps?

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.ts
> +      || `${this.config.outDir}/${entry.replace(/\.(s[ac]ss)$/, this.config.asESModule ? ".$1.js" : ".css")}`;
Please always use `path.join` instead of plain `/` when dealing with paths - ensures cross-platform compatibility.

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.ts
> +    return _.keys(sassGraph.parseFile(`${this.cwd()}${entry}`, {
Please use `path.join` instead of relying on the trailing `/` - ensures cross-platform compatibility.

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.ts
> +    const entryFile = `${this.cwd()}${entry}`;
Same here.

2016-12-23 12:09 UTC, DorianGrey commented on src/styles.ts
> +    return this.config.cwd ? `${this.config.cwd}/` : "";
I'm not the biggest fan of re-evaluating this expression each time this function gets called.

What about using an instance variable for storing this, thus only evaluating this statement once?

2016-12-25 21:08 UTC, sv2dev commented on spec/fixtures/a.entry.scss
> +  version: 1;
Done

2016-12-25 21:08 UTC, sv2dev commented on spec/fixtures/b.scss
> +  version: 1;
Done

2016-12-25 21:08 UTC, sv2dev commented on spec/fixtures/c.scss
> +  version: 1;
Done

2016-12-25 21:08 UTC, sv2dev commented on src/bin/compile-styles.ts
> +console.log(params.outDir);
Done

2016-12-25 21:08 UTC, sv2dev commented on src/styles.spec.ts
> +import {beforeAll, afterAll, it, await} from "jasmine-await";
Done

2016-12-25 21:08 UTC, sv2dev commented on src/styles.spec.ts
> +          compiler.stop();
Done

2016-12-25 21:08 UTC, sv2dev commented on src/styles.ts
> +  private logger: log4js.Logger = StyleCompiler.logger;
It was used by the tests do disable the logging for the whole suite.
Now I simply get the logger by the logger name within the tests.

2016-12-25 21:08 UTC, sv2dev commented on src/styles.ts
> +      filesToWatch.forEach((file: string) => watcher.unwatch(file));
The thing is that you can remove imports in the watched files.
This way we remove all watches and add new ones.
Now we only add and remove the necessary watches.

2016-12-25 21:08 UTC, sv2dev commented on src/styles.ts
> +    return _.keys(sassGraph.parseFile(`${this.cwd()}${entry}`, {
Done

2016-12-25 21:08 UTC, svi3c commented on src/styles.ts
> +        if (pluginConfig) {
I get your point.
But the issue with your suggestion is that there is at least one postcss plugin that is not configurable and does not export a function. See https://github.com/luisrudge/postcss-flexbugs-fixes#usage for example.
My solution now is: check if the export is a function with `_.isFunction()` and call it only in that case.

2016-12-25 21:08 UTC, svi3c commented on src/styles.ts
> +          map: this.config.sourceMaps && {inline: false},
It is larger ... external source maps can also be used in production builds, if you like.

2016-12-25 21:08 UTC, svi3c commented on src/styles.ts
> +      || `${this.config.outDir}/${entry.replace(/\.(s[ac]ss)$/, this.config.asESModule ? ".$1.js" : ".css")}`;
Done

2016-12-25 21:08 UTC, svi3c commented on src/styles.ts
> +    const entryFile = `${this.cwd()}${entry}`;
Done

2016-12-25 21:08 UTC, svi3c commented on src/styles.ts
> +    return this.config.cwd ? `${this.config.cwd}/` : "";
Done

2016-12-27 11:28 UTC, DorianGrey approved these changes

2016-12-27 11:30 UTC, merged